### ISSUE TITLE
titanium cli have to be installed globally

### ISSUE THREAD

**Issue by Cryde** [TheSmiths/ti.es6#8]
Hello !

I know that it seems pretty obvious but since some times we can do "appc ti" instead of "ti" 
So it could be nice if you put in the description that we need to install titanium cli as a npm global npm module

Also you don't check (or notice the user) that titanium cli isn't installed : 
`var installation = spawn('ti', ['config', 'paths.hooks', opt, plugin])`

If you don't have time I could do a pull request for that ! :)

Thanks for this plugin !

**Comment by akfranco** [comment]
Please do the pull request, as this wasn't fixed and I ran into the same issue when trying to walk someone through installing it who's just using Appcelerator Studio.
